### ISSUE TITLE
Default Dashboard resets after Restart

### ISSUE THREAD

**Issue by CreativerName** [daredoes/default-dashboard#8]
So my issue is that the Dropdown Helper is restetting to the default lovelance dashboard after every restart of HA and the Plugin in kinda useless. I really like the effort put into the plugin as it is a fundamental Feature Homeassistant hast implementet yet for some reason.
If it helps I'm running the Home Assistant OS on a respberrypie.

**Comment by leoogermenia** [comment]
I have the same issue...

**Comment by caraar12345** [comment]
A workaround: you can set an automation to run on HA startup. Create the below yaml as an automation, changing `lovelace` to the URL of your dashboard and it will make sure it sticks :)

```yaml
alias: Default Dashboard
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - action: input_select.select_option
    metadata: {}
    data:
      option: lovelace
    target:
      entity_id: input_select.default_dashboard
mode: single
```
